### ISSUE TITLE
More info needed

### ISSUE THREAD

**Issue by labpaw** [da3dsoul/Additional-Buildcraft-Objects#1]
@da3dsoul can you create a forum post at minecraftforum.net or just a issue(maybe release) here at Github with information about your port and with download link? If you do this I'll able to add Additional Buildcraft Objects to 1.7.10 mod list here: http://modlist.mcf.li/version/1.7.10
So, more people will find 1.7.10 port.
Thanks.

**Comment by da3dsoul** [comment]
Oh nice. I use that list all the time. Will do.

**Comment by da3dsoul** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2310397
There we go. And a release jar here as well

**Comment by labpaw** [comment]
Thanks. Additional Buildcraft Objects for 1.7.10 will be added soon on this week.
