### ISSUE TITLE
Distribution Kinesis Pipe

### ISSUE THREAD

**Issue by Chocohead** [da3dsoul/Additional-Buildcraft-Objects#11]
Well, the GUI localisation is completely broken, and the ticks in the GUI itself don't actually do anything:
![2015-02-05_21 02 45](https://cloud.githubusercontent.com/assets/4021725/6069200/61660d68-ad7a-11e4-94e9-a16094af99fc.png)

**Comment by da3dsoul** [comment]
Right, one of those blocks I never use. I'll look at it.

**Comment by da3dsoul** [comment]
I'm just going to remove it, gates and plugs have completely replaced all of its function.

**Comment by da3dsoul** [comment]
Removed in commit.
