### ISSUE TITLE
IC2 exp Insertion Pipe

### ISSUE THREAD

**Issue by Fundaris** [da3dsoul/Additional-Buildcraft-Objects#13]
The Insertion pipe doesn't work for IC2exp. It looks like that it is connected but it keeps the item in pipe and doesn't insert it in to the inventory of the machines. This worked for old abo in 1.7.2.

Tested inserting to Macerator and Ore washing

**Comment by da3dsoul** [comment]
Yes in the newer Buildcraft versions they have the Clay Pipe, which is the insertion pipe, as such I had to adapt this one for other uses (Ender Insertion Pipe).
Honestly, should I put normal insertion pipe functionality back?

**Comment by Fundaris** [comment]
This or change the readme.

**Comment by da3dsoul** [comment]
I'm sorry readme.md, I don't neglect you on purpose...I just forget you exist.

Yeah, I've gotten a few complaints about it, mainly how mine work better.

**Comment by da3dsoul** [comment]
Readded, I'll repackage it here in a couple seconds and repost.
