### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by Sailren** [da3dsoul/Additional-Buildcraft-Objects#14]
hello da3dsoul, i have a report for ya, any idea why this happens?

btw, fastcraft is enabled just to be complete

http://paste.ubuntu.com/10394257/

used abo version: ABO-MC1.7.10-BC6.3-release2.2.jar

forge version is: 10.13.2.1307

**Comment by da3dsoul** [comment]
It's an issue with forge gradle. I'll fix.

**Comment by da3dsoul** [comment]
Hotfixed in release (redownload)
