### ISSUE TITLE
serious power problem

### ISSUE THREAD

**Issue by Sailren** [da3dsoul/Additional-Buildcraft-Objects#15]
when you place a cryo stabilized duct onto a water wheel, this thing can fill a resonant energy cell almost instantly, i use standard configs for thermal dynamics and abo, also works in enderio, the vibrant capacitor has a 100.000 rf/t income with just 1 water wheel

this is what i mean: http://abload.de/img/2015-02-25_19.05.05l2u3l.png

seems the cryo duct has the problem,

**Comment by da3dsoul** [comment]
Dude those pipes look f*****\* awesome. And...hmmm. Show me where to get those and I'll look at it.
If you right click the waterwheel, does it say it is outputting a reasonable amount of energy?

Off topic: You seem to be one of the most thorough users of ABO (or at least the one who gives the most input), have you played with scarygen at all?

**Comment by Sailren** [comment]
i tried it yes, but my computer is a low cost pc, that can play minecraft hardly, at least i doesn't lag so much like my old pc. the pipes are from thermal dynamics, the pipe addon to thermal epansion made my Mr. Tema himself. when i right click it, it tells me 5.000 rf/t, is this 5000 rf/t or 5,000 rf/t? we germans place commas in areas where us people would place a dot

i posted the same screen on teamcofh github and kinglemming answered:

The ducts have been rewritten, but I'm pretty sure the issue here is actually the water wheels.

Either way we should be good in the next release.

**Comment by da3dsoul** [comment]
That would be US, '.' would be decimal so 5 rf/t. It's mainly for debugging, so I didn't bother to format it to locale. He's gotten that far already? Last I checked he was bitching about 1.7 being weird. I'll take a look. Try index 4 with the height limit set at 128, that'll help with lag.

**Comment by da3dsoul** [comment]
For now if you primarily use flux ducts, then use the config for power scaling.

**Comment by Sailren** [comment]
ok

**Comment by da3dsoul** [comment]
Finally started working on this. Funny enough I was programming for another mod and my logs were getting spammed with a FileNotFoundException on diamond fluid pipe textures, and that was enough for me to start working on it.

**Comment by da3dsoul** [comment]
What is that block that tells you the input on the side?

**Comment by da3dsoul** [comment]
I've discovered it is a glitch between BC and TD itself. Connect a buildcraft pipe to a cryostablized fluxduct and then to a battery. Regardless, I fixed it.

**Comment by Sailren** [comment]
the block that tells me the input is a ender io capacitor cell

**Comment by da3dsoul** [comment]
Cool thanks
