### ISSUE TITLE
Why did you readd the Insertion Pipe?

### ISSUE THREAD

**Issue by asiekierka** [da3dsoul/Additional-Buildcraft-Objects#16]
What are its benefits over BC's own?

**Comment by da3dsoul** [comment]
The logic of item movement seems to work nicer. They render items going into things to help keep track of item flow. They are green.

**Comment by asiekierka** [comment]
@da3dsoul - Doesn't BuildCraft's render them too? If not, that's... a bug.

**Comment by da3dsoul** [comment]
Nope, they go into the center and disappear.

**Comment by da3dsoul** [comment]
Hmm looking at it. The code should work. Idk, maybe it's a me only thing. I'll look at it more. My friends are weird and choose ABO's version just because they're green.

**Comment by da3dsoul** [comment]
I'll program more in the morning (night, since I work the graveyard shift). I'll look at it when I'm redoing the naming system for Mob Bottles.

**Comment by da3dsoul** [comment]
OK I don't know what caused it before. I'll post or fix it myself if it happens and I figure out why.

**Comment by asiekierka** [comment]
@da3dsoul - by the way, we have a new ADdons section on the BC forums, you may want to make a thread there: http://mod-buildcraft.com/forums/forumdisplay.php?fid=20

**Comment by da3dsoul** [comment]
I plan to make it so items won't even try to flow into closed iron pipes (really, all should do that anyway).

**Comment by TheLoneWolfling** [comment]
@da3dsoul - please make sure in the process you don't break builds that rely on the current iron pipe bounceback behavior. In particular, a simple (and cheap) way to have a (small) buffer on the input to something is to have an insertion pipe between two iron pipes.

**Comment by da3dsoul** [comment]
Hmm I hadn't thought of that. I'll make both available. If it's already placed, it will default to legacy. Placing down new ones will require smacking with a wrench to enable legacy logic.

**Comment by da3dsoul** [comment]
see https://github.com/da3dsoul/Additional-Buildcraft-Objects/commit/6e7d8c552a43dd2a8740fc7e06ccf76c5b1825f5
