### ISSUE TITLE
Windmill duplication on breaking

### ISSUE THREAD

**Issue by Voidi** [da3dsoul/Additional-Buildcraft-Objects#17]
1. Windmills got duplicated if i break the block direct under the windmill.
2. Are you planing to implement the missing pipes from the prevoius ABO?

**Comment by da3dsoul** [comment]
I'll fix 1.
By the missing pipes, do you mean bounce pipes, stripes pipes, pump pipes, diamond ... pipes, etc?

If so:
Bounce pipe - just an iron pipe and a gate will completely replicate it's effect
Stripe Pipe - completely buildcraft native (and works better)
Pump pipe - aside from being rather cheap for its effect, buildcraft has the pump and floodgate machines that not only do the same thing, but do them more reliably with better control.
Diamond Fluid Pipe - buildcraft native and works better
Diamond Kinesis Pipe - never had a point. pipe plugs are cheaper. you could turn each output on or off, but require the gui, in which case...pipe plugs.

**Comment by asiekierka** [comment]
The bounce pipe was a good thing.

2015-04-02 7:52 GMT+02:00 da3dsoul notifications@github.com:

**Comment by da3dsoul** [comment]
Eh, I suppose for convenience of not needing a gate, I could do that one.
EDIT: I've been curious for a while, is your avatar Uiharu from Toaru... series (Railgun and Index)

**Comment by da3dsoul** [comment]
I cannot for the life of me figure out why part 1 is happening. Windmills drop 2, waterwheels drop 5.

**Comment by da3dsoul** [comment]
I guess I should try to fix this. I just hate seeing labels on my git.

**Comment by da3dsoul** [comment]
Yay I fixed it!
