### ISSUE TITLE
Strange Problem in Combination with Galactricraft

### ISSUE THREAD

**Issue by Voidi** [da3dsoul/Additional-Buildcraft-Objects#18]
Since i installed ABO my Server log gets spammed with something like this:
`Energy network: acceptor took too much energy, offered 1.5258789E-5, took 1.6. buildcraft.transport.TileGenericPipeCompat@2b230fdd`

The problem seem related in the Galacticraft/Buildcraft relation and should be fixed, but as it occured never before my ABO installation i ask you for help.

Secondly, a you aware of the issue that after a Multiplayerserver, restart windmills musst be broken and placed again to work properly?

**Comment by da3dsoul** [comment]
1. Can I get more info on what setup causes the log spam. Versions? How are they powered? What are you powering? I know nothing about what is causing it other than something managed to produce a very small amount of energy and a rounding error happened. I also know that somehow BuildCraft Compat is involved somehow.
2. How are they broken? I am aware of some things I am still fixing.

**Comment by da3dsoul** [comment]
One more thing. For 2, does it also occur with waterwheels? just windmills?

**Comment by Voidi** [comment]
1. After a Server restart, player report that their Windmills are stopped, breaking one in a Network and placing them again helps. Could not reproduce this in Singleplayer. Seems that is not problem with Watermills.

**Comment by da3dsoul** [comment]
OK. I probably already fixed it then.

**Comment by Voidi** [comment]
More Infos
2. Bug: isn't fixed in the latest version
Interessting observation: it is sufficient to break one windmill or waterwheel to all engine on the server running again (running Server with Forge 10.13.2.1291)
1. After the restart, the spamming starts after placing an engine to fix Bug °2

**Comment by da3dsoul** [comment]
Okay we're using the same forge. Do they just not produce energy? Do they spin? If you right click with nothing in hand does it say it is producing energy? What color are they? Do they look like this?
http://i58.tinypic.com/2wqr2xl.jpg
There are a lot of ways something can not work, as evident in the picture.

The log spam looks like a rounding issue Galacticraft had back in December. I posted on micdoodle8's thread to see if he knew.

**Comment by Voidi** [comment]
Neither Machine or Batteries receive Energy, the spin, right clicking say '0 RF/t, from 0 RF/t expected', and they are red colored.

**Comment by da3dsoul** [comment]
Okay, that gives me a pretty good idea of what it is doing. Are the windmills visually connected to the pipes?

**Comment by da3dsoul** [comment]
I posted a release with some log spamming. Delete or move your logs and run it. Then post it for me (or at least the parts that say 'Windmill at...'). There is also a minor change that might help them fix themselves.

**Comment by Voidi** [comment]
Ok here you go:
[Logs](http://www.dertobi.name/~tobias/upload/Minecraft/logs/abo/)
The First one is with config setting `D:WindmillEnergyScalar=0.9`, the second one with the standard value, and the third one is with the breaking and placing a windmill to reactivate them.
And yes they are visually connected to pipes.

**Comment by da3dsoul** [comment]
Well, I told you it would spam your log. On the bright side I think I may have fixed it. At least I figured out why it happens.

**Comment by da3dsoul** [comment]
Try logspam2 release. I rewrote the way scalars are initialized and hopefully solves this.

**Comment by da3dsoul** [comment]
Logspam3 with a hopeful fix for the galacticraft rounding issue.

**Comment by Voidi** [comment]
Using Logspam3 , at least the log spamming of the original message occurs but with decreased frequency.

**Comment by da3dsoul** [comment]
Decreased frequency is probably as good as I will get. In the logs where the windmills were not working, the message still occurred. Meaning there is another mood that has the same issue. How about windmills and waterwheels? Are they working?

**Comment by Voidi** [comment]
Yes they are working, and the original Message of 'Energy Network' is very rare.
I will investigate the occurance and gather more info.

**Comment by da3dsoul** [comment]
I'm going to have a new release here in about an hour. It'll remove the log spam.
