### ISSUE TITLE
Remove pipes added by BC6.2

### ISSUE THREAD

**Issue by asiekierka** [da3dsoul/Additional-Buildcraft-Objects#2]
BC 6.2 added the Clay Insertion Pipe and the Diamond Liquid Pipe from ABO. (Yes, I got permission to integrate the code directly)

**Comment by da3dsoul** [comment]
I will leave insertion pipes in (kind of, I left them in for the ender interaction so they will be changed and renamed). I already have plans to remove diamond fluid pipes. I am just lazy.

**Comment by da3dsoul** [comment]
Removed
