### ISSUE TITLE
Releases on Curseforge

### ISSUE THREAD

**Issue by labpaw** [da3dsoul/Additional-Buildcraft-Objects#25]
What do you think about making a page for Additional Buildcraft Objects on [Curseforge](http://minecraft.curseforge.com/)? Many mods already there and it's a better place for mods however you can continue support MCF thread too as many other modders doing.

**Comment by da3dsoul** [comment]
http://minecraft.curseforge.com/mc-mods/230250-additional-buildcraft-objects

This needs to be approved by mods, but it is there.

**Comment by da3dsoul** [comment]
Nope, this isn't going to happen. Curse shot me down as I picked up the project without express written transfer of rights from Flow86. I also didn't write everything from scratch, have some of the icons the same, and didn't start the project with a different name. By that definition, I am violating the license set forth by Flow86. Nonetheless, unless he decides to exist again and tells me to stop, I am going to continue this. But Curse is correct, so I can't host there.

**Comment by MapleSight** [comment]
Ahhhh, didn't see this. Thanks for the info.

**Comment by MapleSight** [comment]
Any news on this? Maybe you could ask Flow for permission? He's alive: https://github.com/Flow86

@Flow86
