### ISSUE TITLE
buildcraft 7

### ISSUE THREAD

**Issue by ghost** [da3dsoul/Additional-Buildcraft-Objects#28]
are you going to update to buildcraft 7? or is it compatible already?

**Comment by da3dsoul** [comment]
I'm waiting for a stable release (not a "stable" release, but one that actually has few bugs) to officially support it. You can try it as is, but I recommend starting a new world assuming it doesn't crash on startup. If you try it and it works, please let me know.

**Comment by Sailren** [comment]
"Time to bump BuildCraft 7 to an "RC" state: that is, we think it's stable, but we can't be sure."

http://mod-buildcraft.com/buildcraft-6416-stable-705-rc-compat-703-rc.html

**Comment by da3dsoul** [comment]
Yeah, I'm already working on it.

**Comment by Sailren** [comment]
great, is it hard to update?

**Comment by da3dsoul** [comment]
Yeah, they redid fluid pipes.

**Comment by Sailren** [comment]
for forge fluid update?

**Comment by da3dsoul** [comment]
No, it already worked for that. buildcraft changed the PipeTransportFluids system to make less network spam, but I relied on the extra space in the packets.

**Comment by Sailren** [comment]
and now?

**Comment by MapleSight** [comment]
Updates take quite a while to do. We all are looking forward to the ABO update and all we can do is wait.

**Comment by da3dsoul** [comment]
Due to issues, the reinforced pipes won't work quite as well as I'd like, but people are waiting on a build that works.

**Comment by asiekierka** [comment]
@da3dsoul - https://github.com/BuildCraft/BuildCraft/commit/7f6b2e72d167f1b8f96b7f2a1de2921339585ec7 <- starting with BC 7.0.10, we detect large fluid pipe capacities.

**Comment by da3dsoul** [comment]
Cool, with that, everything in ABO should be working again.

**Comment by da3dsoul** [comment]
Mk, verified everything is working now.

**Comment by Sailren** [comment]
you are a hero
