### ISSUE TITLE
client crash when trying to wrench a diode pipe

### ISSUE THREAD

**Issue by Sailren** [da3dsoul/Additional-Buildcraft-Objects#31]
http://paste.ubuntu.com/11713069/

**Comment by da3dsoul** [comment]
Apparently there was a code change in BC 7.0.9. My next rebase is going to be on 7.0.10 unless they take too long to release it.

Wrenching an iron/wood/etc. pipe sets it to the direction you hit in. (asie)
is probably what broke it.

**Comment by asiekierka** [comment]
Yes. I didn't consider that other people are using PipeLogicIron, sorry. I will restore that part of the code in 7.0.10.
