### ISSUE TITLE
ABO Fluid Pipes Not Rendering Fluids

### ISSUE THREAD

**Issue by da3dsoul** [da3dsoul/Additional-Buildcraft-Objects#35]
The fluid travels smooth, though.

**Comment by da3dsoul** [comment]
I'm prone to forget these things.

**Comment by da3dsoul** [comment]
@asie did anything significant change there?

**Comment by asiekierka** [comment]
Yes, PipeTransportRenderer now exists and has a map of PipeTransports to
their renderers.

2015-10-04 16:21 GMT+02:00 da3dsoul notifications@github.com:

**Comment by da3dsoul** [comment]
Good to know, now I know what to look for

**Comment by da3dsoul** [comment]
Nice that it is a map, so I can just pull the Fluid Renderer and assign it to PipeTransportFluidsReinforced

**Comment by da3dsoul** [comment]
Instead of making a new one pointlessly.

**Comment by da3dsoul** [comment]
Also, beautiful work on the rendering cleanup. Fluid pipe propagation is still broken when pipes cross often.
