### ISSUE TITLE
Kinesis Diode Suggestion

### ISSUE THREAD

**Issue by xannor** [da3dsoul/Additional-Buildcraft-Objects#37]
It would be nice if the Kinesis Diode output direction could be set with gate controls, similar to the iron transport pipe.

**Comment by da3dsoul** [comment]
Iron pipes can do that now? Mk. Give me a few hours. I'm working on a different mod.

**Comment by xannor** [comment]
no hurries, just something I noticed while tinkering with power routing ideas. I think iron pipes had a gate control since bc6, but I doubt many people use them over just leaving them in a direction, or using a diamond pipe.

**Comment by da3dsoul** [comment]
Wrote it up, testing now.

**Comment by da3dsoul** [comment]
Mk, all better. I'll clean up something else I've been working on and post a release. People tend to be upset when they right click with a vanilla item and their house gets terraformed.
