### ISSUE TITLE
mob bottles

### ISSUE THREAD

**Issue by meelock** [da3dsoul/Additional-Buildcraft-Objects#38]
i think mob bottles are kind of overpowered, and i'm wondering if you could add a config option to disable them, just so that players who i play with don't abuse them.

**Comment by da3dsoul** [comment]
Sure, they are a convenient tool, but also a one hit kill if you Chuck it in lava

**Comment by da3dsoul** [comment]
I was wondering if anyone used them. I prefer them to other things like the golden lasso from extra utils. Plus, nothing else I've seen has special handling for mine carts.
