### ISSUE TITLE
Strange crash after server restart.

### ISSUE THREAD

**Issue by xannor** [da3dsoul/Additional-Buildcraft-Objects#39]
[crash-2015-11-28_13.12.50-server.txt](https://github.com/da3dsoul/Additional-Buildcraft-Objects/files/46391/crash-2015-11-28_13.12.50-server.txt)

Got this server crash after a restart, I had just added MineTweaker, mod tweaker, and content tweaker when it first occurred and backed down to before I added them, but I still get it. Server was fine before I added those mods.

**Comment by da3dsoul** [comment]
Interesting

**Comment by da3dsoul** [comment]
Try this: https://dl.dropboxusercontent.com/u/31454410/ABO-MC1.7.10-BC7.1release4.0.4.jar

**Comment by xannor** [comment]
it is a fairly new world so I think the only ABO items I have in use are two insertion pipes (I didn't have clay) so I wonder if the server was shutdown with an item traversing the pipe. I'm trying to load the world in mcedit to see if I delete those two pipes, the server will start.

**Comment by xannor** [comment]
just noticed your post, trying it now. have not used mcedit yet.

**Comment by da3dsoul** [comment]
That won't help. It is an obfuscation error of some kind on a call to MathHelper.StringNullOrEmpty(string). I don't know why these things happen, but every once in awhile they do, and the solutions generally make no more sense than the cause.

**Comment by da3dsoul** [comment]
I blame Samsung and Bukkit.

**Comment by xannor** [comment]
it worked thanks.

**Comment by da3dsoul** [comment]
Cool. Good to know.
