### ISSUE TITLE
Windmill

### ISSUE THREAD

**Issue by Chocohead** [da3dsoul/Additional-Buildcraft-Objects#4]
I've got the latest version of Buildcraft, and it seems windmills refuse to connect to kinetic pipes:
![2014-12-28_21 41 24](https://cloud.githubusercontent.com/assets/4021725/5565052/5921b882-8eda-11e4-8199-2841fc562124.png)
Am I doing something wrong, or are they broken?

**Comment by da3dsoul** [comment]
Connect it to a wooden or emerald kinesis pipe. It behaves similarly to engines.

**Comment by Chocohead** [comment]
Ohhhh, that makes sense.

All good now.
