### ISSUE TITLE
[Bug] Rendering item - Bricks

### ISSUE THREAD

**Issue by Markezzz** [da3dsoul/Additional-Buildcraft-Objects#42]
The game crashes if I put Bricks in a Crafting Table.

You can see the details in the Crash-Log: [crash-2016-03-31_05.54.33-client.txt](https://github.com/da3dsoul/Additional-Buildcraft-Objects/files/196965/crash-2016-03-31_05.54.33-client.txt)

**Comment by da3dsoul** [comment]
Hmmm. That is definitely my fault. It would be nice if the log said anything useful, though. Rendering logs never do... Anyway, looking at it now.

**Comment by da3dsoul** [comment]
Try this https://dl.dropboxusercontent.com/u/31454410/ABO-MC1.7.10-BC7.1release4.0.8.jar

**Comment by Markezzz** [comment]
I get the same error with the new version.
Here are all new log files for you: [logs-latest.zip](https://github.com/da3dsoul/Additional-Buildcraft-Objects/files/197346/logs-latest.zip)

**Comment by da3dsoul** [comment]
Try this https://dl.dropboxusercontent.com/u/31454410/ABO-MC1.7.10-BC7.1release4.0.8.jar

**Comment by da3dsoul** [comment]
it is different, but same link

**Comment by Markezzz** [comment]
Thanks, for the fast response.
But the error is alive. :/ 
The Logs for you: [logs-latest2.zip](https://github.com/da3dsoul/Additional-Buildcraft-Objects/files/197401/logs-latest2.zip)

**Comment by da3dsoul** [comment]
I updated that link again. Go ahead and try it.

**Comment by Markezzz** [comment]
You got it! Now it works fine. :)
Thanks!

**Comment by da3dsoul** [comment]
If that is the case, I think I finally figured out an issue to another mod
