### ISSUE TITLE
Vanilla Bricks in crafting table causes game crash

### ISSUE THREAD

**Issue by thegoogleguy** [da3dsoul/Additional-Buildcraft-Objects#43]
In my pack, I've had an issue where whenever you'd put a vanilla bricks block in a crafting table with no other items, the game would crash to desktop. Here's a sample crash log: http://pastebin.com/9kAmMdtH

I couldn't find any info on Google about what could be causing this. If I looked in NEI for recipes utilizing the vanilla bricks block, this recipe would show up: http://imgur.com/a4foQ6E I'm guessing that recipe isn't supposed to be there, but using MineTweaker I was unable to remove it.

So, I began going through the mods in my pack 1 by 1 until I found that the recipe disappeared after removing this mod from the pack. The game crash also stopped after removing the mod. I'm using the latest release 4.0.8 on BuildCraft 7.1.16.

Any ideas on how to fix this? Thanks in advance.

**Comment by da3dsoul** [comment]
Right! I already fixed that. I'll release in a few

**Comment by da3dsoul** [comment]
See #42

**Comment by thegoogleguy** [comment]
OK, thank you very much!
