### ISSUE TITLE
ScaryGen Water Replacement isn't working

### ISSUE THREAD

**Issue by Shahelion** [da3dsoul/Additional-Buildcraft-Objects#51]
I tried using Ars Magica 2's Liquid Etherium, but it just generates with water every time. I can't find hardly any information on ScaryGen as it is. Should I be using a different name than "arsmagica2:liquidEssence"?

EDIT: Have also tried Mystcraft:BlockFluidMyst (black ink), also did nothing.

**Comment by da3dsoul** [comment]
Can you screenshot the UI? I know how it works, but I can't remember what I called things exactly. I don't want to say something else and just confuse you.

**Comment by da3dsoul** [comment]
Nvm I just read the code. You need to put that in the box (obviously), then press the `?` button next to it. It'll say `OK` if it accepted a valid block name. Then, you can hit the save button or whatever it's called.

**Comment by da3dsoul** [comment]
I know it works. I've done some dumb things like lava, liquified redstone, etc

**Comment by Shahelion** [comment]
I tried clicking the ? button, but it never did anything. Wasn't sure what it was supposed to do. Does it just take longer than expected?

**Comment by da3dsoul** [comment]
Nothing? It should become an `X` if it's not recognized or `OK` if it is. The state resets if the text in the box changes

**Comment by da3dsoul** [comment]
I can spin up a 1.7.10 pack with BuildCraft and ABO to check on it. Are you using a pack, or just a list of mods?

**Comment by Shahelion** [comment]
A list of mods. https://gist.github.com/Zsashas/5f42f57a58104c0e0a3d4a2c25a051cd

Yeah, it just remains a ? no matter how long I wait.

**Comment by da3dsoul** [comment]
It should be less than 1s, so yeah I'll look at it. Have you used F3+H to verify the ID of the block?

**Comment by Shahelion** [comment]
No, but I used both NEI's fluid data dump and MineTweaker's /identify command.

Just tested, the ? doesn't even do anything with vanilla water.

**Comment by Shahelion** [comment]
My attempted settings
![2020-01-19_08 41 02](https://user-images.githubusercontent.com/6917535/72684670-7673e180-3a97-11ea-8fce-52de4ab3c680.png)

**Comment by da3dsoul** [comment]
That's odd

**Comment by da3dsoul** [comment]
Yeah I'll look

**Comment by Shahelion** [comment]
Update: it worked! The ? changed to a !, it just took a long time

**Comment by Shahelion** [comment]
So, it works nearly as expected now. The only weird thing is how there's Erebus Umberstone now generating in the overworld, but that might be a separate issue...
![2020-01-19_08 56 35](https://user-images.githubusercontent.com/6917535/72684959-ec794800-3a99-11ea-96bb-abd0ca4bd405.png)
![2020-01-19_08 57 57](https://user-images.githubusercontent.com/6917535/72684961-ed11de80-3a99-11ea-9f03-40cf0344998b.png)

**Comment by da3dsoul** [comment]
Did you enable GeoStrata Gen? That will take the color of the biome and pair stone like blocks to it for stone. It's a thing that I did for a more natural generation pattern without BOP or something similar.

**Comment by Shahelion** [comment]
Ohhhh I thought that was a toggle for the GeoStrata mod.

**Comment by da3dsoul** [comment]
Nah, it replaces GeoStrata's world gen with full stone replacement,
primarily GeoStrata's stone, but it'll take stone from other mods, though
it looks like there are some that should probably be blacklisted.

**Comment by Shahelion** [comment]
So I've been waiting for the ? to change for like 20 minutes now, maybe it isn't working as well as I thought...

Tried to make a new world with the same ocean block

Also there is pretty much no feedback from that ? button. It doesn't even feel like I'm clicking it, and a progress bar or something, if possible, would be neat. Or even something in the console.

**Comment by da3dsoul** [comment]
Sadly, progress or something wouldn't be possible without some tweaking. If I can reproduce that lag, then I'll see about making it faster and/or some form of progress. All of the lag is in one line, and it's a built-in Minecraft call.
```
if((block1 = Block.getBlockFromName(block)) != null)
```

**Comment by Shahelion** [comment]
I have no idea how I got it to work that one time, it won't work anymore.

**Comment by da3dsoul** [comment]
Any chance I can get you to zip your mods and config folders? Finding and downloading all of those mod versions will take longer than fixing this, most likely.

I don't know where you are, but mega or something works. I'd normally just hand you a drop link for my Nextcloud, but it decided to kill itself yesterday....

**Comment by Shahelion** [comment]
This took a lot less time to upload than I expected...hope this works.

https://drive.google.com/file/d/1sX_Vh6lYXy92POw38f0lcVUUKJxpI5qk/view?usp=sharing

**Comment by Shahelion** [comment]
It seems that once a block has been "approved", it continues to use that block for any future worldgens using ScaryGen unless another block is "approved" instead. I made a world with Liquid Etherium, then tried to make another one with Ethereal Luma, but it was Etherium instead still. I didn't wait as long after clicking the ? button. 

Is there a way, perhaps via config option, to just tell it to use a block regardless of whether it is "safe"? Seems like the main problem here is the speed with which it checks the given block.

Last question, would it be possible to have a separate option to replace the water in rivers, so I could have different blocks for rivers and oceans?

**Comment by Shahelion** [comment]
Holy shit I figured it out.

Don't click the ? button, just hit the enter key. I feel stupid now for not figuring that out sooner lol.

**Comment by da3dsoul** [comment]
The rivers are something that I looked into before. I don't remember. I could look into it again. I'm considering updating part of the mod to 12.2 and maybe 14...idk yet

**Comment by Shahelion** [comment]
Thank you for putting up with me lol

**Comment by da3dsoul** [comment]
Np
