### ISSUE TITLE
crash with buildcraft 6.3

### ISSUE THREAD

**Issue by Sailren** [da3dsoul/Additional-Buildcraft-Objects#6]
http://paste.ubuntu.com/9682477/

**Comment by Chocohead** [comment]
I got the same thing, Buildcraft changelog mentioned removing unused functions in the core: https://github.com/BuildCraft/BuildCraft/blob/master/buildcraft_resources/changelog/6.3.0#L51

**Comment by da3dsoul** [comment]
I'll look at it.

**Comment by da3dsoul** [comment]
I'll let you know that 6.3 is BETA, as in there might be things that crash even if my code is perfect. We'll see.

**Comment by da3dsoul** [comment]
PS. I have today off due to snow. Don't expect a 2 hour response or fix to happen often.

**Comment by Sailren** [comment]
no problem

**Comment by da3dsoul** [comment]
I made all the build errors go away. Now to test everything.

**Comment by da3dsoul** [comment]
Ok it works.

**Comment by da3dsoul** [comment]
I marked the release as a prerelease because I've barely tested it. I will change if there are no problems.
